### ISSUE TITLE
Liscense?

### ISSUE THREAD

**Issue by ghost** [VRSpeedruns/VRSpeed.run#1]
What is the license for this project?

**Comment by bigfoott** [comment]
Hello! Sorry, this totally slipped my mind. I've decided to go for [CC-BY-NC-SA](https://github.com/VRSpeedruns/VRSpeed.run/blob/master/LICENSE.md) as that's the license the Speedrun.com API is under, and it seems like a fair choice.

Added in https://github.com/VRSpeedruns/VRSpeed.run/commit/1782909a7a473545eccf7b8a82aceed7a131f18e. Thanks for bringing this up!

**Comment by bigfoott** [comment]
What are you thinking of working on with it? Out of curiousity 🙂

**Comment by ghost** [comment]
I was going to swap out the games json for every game on speedrun.com :)

**Comment by ghost** [comment]
If you don't mind, how would I run this? I got a simple php+apache server running but every thing except root is a 404 and and the index page is really broken

**Comment by bigfoott** [comment]
> I was going to swap out the games json for every game on speedrun.com :)

Hey! So originally I was going to basically have the site work like you want it to, but I was concerned with if doing something like that would be allowed in the Speedrun.com Terms of Use. I talked to a SR.C staff member and explained my position, and they were fine with the way I have the site currently set up, as it's acting similar to a game series on the main site.

Please don't take this personally, but I'm not really comfortable with the project being used to access the entire site. I don't want it to more or less replace the main site while using their API, if that makes sense.

> If you don't mind, how would I run this? I got a simple php+apache server running but every thing except root is a 404 and and the index page is really broken

I'll be honest, I hadn't really thought about anyone trying to set up their own instance of the site. 😅 There is a lot of hacky stuff not included in the repo, so in its current state it isn't really possible to set up your own version. This has given me the idea to basically strip this project down to what is essentially a template, which would work without too much of that hackiness. Included in that would also be information on how to do the required not-in-repo stuff :)

I'd recommend waiting for that, as it would be way easier than trying to hack through and fix a bunch of things blindly.

But again, I'm not really comfortable with it being used to access all of Speedrun.com. I would prefer it be used in a way to how the main site is set up; to easily group together games. For example, it could be used as an easier way to view game series like the Half-Life series, or even as a way to group together the main Valve source games into a single location.

Sorry about this! I'll let you know here when I've set up the "template" project :)

**Comment by bigfoott** [comment]
Oh also, I've moved the project over to AGPLv3.0 license (https://github.com/VRSpeedruns/VRSpeed.run/commit/7c603b1eacd8783222e33c97b659e199467c2923), as I learned CC licenses aren't really for software.

**Comment by ghost** [comment]
Ah I see. I would totally do a Valve based one as I actually run source games myself. I totally get it, thanks for that lengthy writeup.

**Comment by bigfoott** [comment]
No problem! I don't have an ETA on when the template project will be finished, as the majority of VRSR was done over the summer with plenty of free time (that I no longer have sadly). I'll reply here whenever it's done.

**Comment by ghost** [comment]
alright!
