### ISSUE TITLE
Game Request: Bait!

### ISSUE THREAD

**Issue by sosaceace11** [VRSpeedruns/VRSpeed.run#3]
**Speedrun.com URL**: https://www.speedrun.com/bait?h=Any-Glitchless&x=jdro99xd-j84gom28.4lxme6gq

**Primary Color** (Optional):

**Other** (Optional):

**Comment by bigfoott** [comment]
Thanks for the game request! Added in https://github.com/VRSpeedruns/VRSpeed.run/commit/bfc1579fc96cfbc268dc36d9c5ceb87628a92176.

https://vrspeed.run/bait
