### ISSUE TITLE
Game Request: The 7th Guest VR

### ISSUE THREAD

**Issue by darkshoxx** [VRSpeedruns/VRSpeed.run#4]
**Speedrun.com URL**: https://www.speedrun.com/t7gvr

**Primary Color** (Optional): red

**Other** (Optional):

**Comment by bigfoott** [comment]
Thanks for the request! Game added in https://github.com/VRSpeedruns/VRSpeed.run/commit/083b127c6f782c29f97fa5eaa36150741b8dbd75.
