### ISSUE TITLE
Game Request: The Red Stare

### ISSUE THREAD

**Issue by the-monika** [VRSpeedruns/VRSpeed.run#6]
**Speedrun.com URL**:https://www.speedrun.com/The_Red_Stare

**Primary Color** (Optional):

**Other** (Optional):

**Comment by bigfoott** [comment]
Thanks for the request! Game added in https://github.com/VRSpeedruns/VRSpeed.run/commit/083b127c6f782c29f97fa5eaa36150741b8dbd75.
