### ISSUE TITLE
Game Request: <Angry Birds VR/AR: Isle of Pigs>

### ISSUE THREAD

**Issue by jackzfiml** [VRSpeedruns/VRSpeed.run#8]
**Speedrun.com URL**: https://www.speedrun.com/angry_birds_vr_isle_of_pigs_

**Primary Color** (Optional): no

**Other** (Optional): no

**Comment by bigfoott** [comment]
Added in https://github.com/VRSpeedruns/VRSpeed.run/commit/3db05488a52c4196df79d3f58c8c940927ff1912. Thanks!
